name: Deploy to GAE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Authenticate to Google Cloud using the Service Account Key
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_DEV_KEY }}'  # Authenticate using the service account key

      # Set GCP Project ID
      - name: Set GCP Project
        run: gcloud config set project test-dev-4321
      
      # Deploy to App Engine
      - name: Deploy to App Engine
        run: |
          cd ./my-react-app-portal
          gcloud app deploy app.yaml --quiet
